# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       kde5-kate

# >> macros
# << macros

Summary:    Advanced KDE editor applications
Version:    4.97.0
Release:    1
Group:      System/Base
License:    GPLv2+
URL:        http://www.kde.org
Source0:    %{name}-%{version}.tar.xz
Source100:  kde5-kate.yaml
Source101:  kde5-kate-rpmlintrc
Requires:   kde5-filesystem
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Xml)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(Qt5Concurrent)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  pkgconfig(Qt5Script)
BuildRequires:  pkgconfig(Qt5Sql)
BuildRequires:  kde5-rpm-macros
BuildRequires:  extra-cmake-modules
BuildRequires:  qt5-tools
BuildRequires:  kf5-umbrella
BuildRequires:  kf5-kconfig-devel
BuildRequires:  kf5-kdoctools-devel
BuildRequires:  kf5-kguiaddons-devel
BuildRequires:  kf5-ki18n-devel
BuildRequires:  kf5-kinit-devel
BuildRequires:  kf5-kjobwidgets-devel
BuildRequires:  kf5-kio-devel
BuildRequires:  kf5-kparts-devel
BuildRequires:  kf5-ktexteditor-devel
BuildRequires:  kf5-kwindowsystem-devel
BuildRequires:  kf5-kitemmodels-devel
BuildRequires:  kf5-kxmlgui-devel
BuildRequires:  desktop-file-utils
Provides:   kate = %{version}-%{release}
Provides:   kwrite = %{version}-%{release}
Conflicts:   kde-runtime
Conflicts:   kwrite
Conflicts:   kate

%description
An advanced editor component which is used in numerous KDE applications
requiring a text editing component.


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
%kde5_make
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
%kde5_make_install
# << install pre

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%doc AUTHORS COPYING-GPL3 COPYING-LGPL3 COPYING.LIB README.md
%{_kde5_bindir}/kwrite
%{_kde5_bindir}/kate
%{_kde5_libdir}/libkdeinit5_kate.so
%{_kde5_libdir}/libkdeinit5_kwrite.so
%{_kde5_plugindir}/*.so
%{_kde5_sysconfdir}/xdg/katerc
%{_kde5_datadir}/kate/kateui.rc
%{_kde5_datadir}/kwrite/kwriteui.rc
%{_kde5_datadir}/katefiletree
%{_kde5_datadir}/katesearch
%{_kde5_datadir}/kateproject
%{_kde5_datadir}/katekonsole
%{_kde5_datadir}/katectags
%{_kde5_datadir}/katesql
%{_kde5_datadir}/katexmltools
%{_kde5_datadir}/kateopenheaderplugin
%{_kde5_datadir}/katecloseexceptplugin
%{_kde5_datadir}/kategdb
%{_kde5_datadir}/katebuild
%{_datadir}/icons/hicolor/*/actions/*
%{_datadir}/applications/*.desktop
%{_datadir}/kservices5/*.desktop
%{_datadir}/doc/HTML/en/kate
%{_datadir}/doc/HTML/en/katepart
%{_datadir}/man/man1/kate.1.gz
# >> files
# << files
